version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PARAM1=value1
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
